import Foundation

struct WeaponDefinition: Codable { let id: String; let damage: Double; let fireRate: Double; let magazineCapacity: Int; let reserveAmmo: Int; let reloadDuration: Double; let recoil: Double; let spread: Double }
final class PlayerWeaponState { let definition: WeaponDefinition; private(set) var magazine: Int; private(set) var reserve: Int; private(set) var isReloading=false; private(set) var reloadRemaining: TimeInterval=0; init(definition: WeaponDefinition){self.definition=definition;magazine=definition.magazineCapacity;reserve=definition.reserveAmmo} @discardableResult func fire()->Bool{guard !isReloading,magazine>0 else{return false};magazine-=1;return true} @discardableResult func beginReload()->Bool{guard !isReloading,magazine<definition.magazineCapacity,reserve>0 else{return false};isReloading=true;reloadRemaining=definition.reloadDuration;return true} func tick(dt:TimeInterval){guard isReloading else{return};reloadRemaining=max(0,reloadRemaining-dt);guard reloadRemaining==0 else{return};let n=definition.magazineCapacity-magazine;let t=min(n,reserve);magazine+=t;reserve-=t;isReloading=false} }
struct ReadableAssetRecord: Codable { let originalPath:String;let generatedOutputPath:String;let detectedFormat:String;let assetClass:String;let size:Int;let sha256:String;let status:String; enum CodingKeys:String,CodingKey{case originalPath="original_path",generatedOutputPath="generated_output_path",detectedFormat="detected_format",assetClass="asset_class",size,sha256,status} }
struct ReadableAssetManifest: Codable { let schema:String;let policy:String;let records:[ReadableAssetRecord] }
struct RuntimeSpawnPoint: Codable { let team:Team;let x:Double;let y:Double;let z:Double }
struct RuntimeBox: Codable { let x:Double;let y:Double;let z:Double;let sx:Double;let sy:Double;let sz:Double }
struct RuntimeObjective: Codable { let type:String;let x:Double;let y:Double;let z:Double;let radius:Double;let plantDuration:Double;let fuseDuration:Double;let defuseDuration:Double }
struct RuntimeMapDefinition: Codable { let name:String;let format:String;let worldScale:Double;let spawnPoints:[RuntimeSpawnPoint];let boxes:[RuntimeBox];let objective:RuntimeObjective? }
enum GameDataLoader { static func loadValidationMap(bundle:Bundle = .main)throws->RuntimeMapDefinition{guard let u=bundle.url(forResource:"validation_map",withExtension:"json") else{throw NSError(domain:"BO2IOSCS.GameData",code:1)};let m=try JSONDecoder().decode(RuntimeMapDefinition.self,from:Data(contentsOf:u));guard m.format=="bo2ioscs-normalized-map-v1",!m.spawnPoints.isEmpty else{throw NSError(domain:"BO2IOSCS.GameData",code:2)};return m} static func loadReadableAssetManifest(bundle:Bundle = .main)throws->ReadableAssetManifest{guard let u=bundle.url(forResource:"readable_asset_manifest",withExtension:"json") else{throw NSError(domain:"BO2IOSCS.GameData",code:4)};let m=try JSONDecoder().decode(ReadableAssetManifest.self,from:Data(contentsOf:u));guard m.schema=="bo2ioscs-readable-asset-manifest-v1",!m.records.isEmpty,!m.records.contains(where:{$0.originalPath.lowercased().hasSuffix(".ff")}) else{throw NSError(domain:"BO2IOSCS.GameData",code:5)};return m} static func loadWeapons(bundle:Bundle = .main)throws->[WeaponDefinition]{guard let u=bundle.url(forResource:"weapons",withExtension:"json") else{throw NSError(domain:"BO2IOSCS.GameData",code:3)};return try JSONDecoder().decode([WeaponDefinition].self,from:Data(contentsOf:u))} }
enum Team:String,Codable{case attack,defense}; enum ObjectiveState:String,Codable{case idle,planting,planted,defusing,detonated,defused}
final class BotState { let id:Int;let team:Team;var health=100;var shots=0;var deaths=0;var x=0.0;var y=0.0;var z=0.0;var alive:Bool{health>0};init(id:Int,team:Team){self.id=id;self.team=team} }
final class MatchSimulation {
 private(set)var round=1;private(set)var scoreAttack=0;private(set)var scoreDefense=0;private(set)var elapsed:TimeInterval=0;private(set)var shotsFired=0;private(set)var objectiveTicks=0;private(set)var objectiveState:ObjectiveState = .idle;private(set)var eliminations=0;private(set)var playerShotsFired=0;private(set)var playerHits=0;private(set)var playerEliminations=0;var playerCombatIntegrated:Bool{playerShotsFired>0&&playerHits>0};private(set)var objectiveElapsed:TimeInterval=0;private var botCombatAccumulator:TimeInterval=0;let bots:[BotState];let objective:RuntimeObjective?;private let spawnPoints:[RuntimeSpawnPoint]
 init(botCount:Int=4,objective:RuntimeObjective?=nil,spawnPoints:[RuntimeSpawnPoint]=[]){self.objective=objective;self.spawnPoints=spawnPoints;bots=(0..<botCount).map{BotState(id:$0,team:$0.isMultiple(of:2) ? .attack:.defense)};applySpawnPoints()}
 private func applySpawnPoints(){for b in bots{let s=spawnPoints.filter{$0.team==b.team};guard !s.isEmpty else{continue};let p=s[(b.id/2)%s.count];b.x=p.x;b.y=p.y;b.z=p.z}}
 func playerSpawn(team:Team)->RuntimeSpawnPoint?{spawnPoints.first{$0.team==team}}
 func isInsideObjective(x:Double,y:Double,z:Double)->Bool{guard let o=objective else{return false};let dx=x-o.x,dy=y-o.y,dz=z-o.z;return dx*dx+dy*dy+dz*dz <= o.radius*o.radius}
 @discardableResult func beginPlant(playerX:Double,playerY:Double,playerZ:Double)->Bool{guard objective != nil,objectiveState == .idle,isInsideObjective(x:playerX,y:playerY,z:playerZ) else{return false};objectiveState = .planting;objectiveElapsed=0;return true}
 @discardableResult func beginDefuse(playerX:Double,playerY:Double,playerZ:Double)->Bool{guard objective != nil,objectiveState == .planted,isInsideObjective(x:playerX,y:playerY,z:playerZ) else{return false};objectiveState = .defusing;objectiveElapsed=0;return true}
 func beginPlant(){guard let o=objective else{return};_ = beginPlant(playerX:o.x,playerY:o.y,playerZ:o.z)};func beginDefuse(){guard let o=objective else{return};_ = beginDefuse(playerX:o.x,playerY:o.y,playerZ:o.z)}
 @discardableResult func fire(weapon:WeaponDefinition,from s:Int,at t:Int)->Bool{guard s != t,bots.indices.contains(s),bots.indices.contains(t),bots[s].alive,bots[t].alive,bots[s].team != bots[t].team else{return false};bots[s].shots+=1;shotsFired+=1;bots[t].health=max(0,bots[t].health-Int(weapon.damage.rounded()));if bots[t].health==0{bots[t].deaths+=1;eliminations+=1;resolveEliminationRoundIfNeeded()};return true}
 @discardableResult func playerFire(weapon:WeaponDefinition,at t:Int)->Bool{playerShotsFired+=1;guard bots.indices.contains(t),bots[t].alive else{return false};let alive=bots[t].alive;bots[t].health=max(0,bots[t].health-Int(weapon.damage.rounded()));playerHits+=1;shotsFired+=1;if alive && !bots[t].alive{bots[t].deaths+=1;eliminations+=1;playerEliminations+=1;resolveEliminationRoundIfNeeded()};return true}
 private func resolveEliminationRoundIfNeeded(){let a=bots.contains{$0.team == .attack && $0.alive},d=bots.contains{$0.team == .defense && $0.alive};if !d&&a{scoreAttack+=1;resetRound()}else if !a&&d{scoreDefense+=1;resetRound()}}
 private func resetRound(){round+=1;elapsed=0;objectiveElapsed=0;objectiveState = .idle;for b in bots{b.health=100};applySpawnPoints()}
 func botCombatTick(dt:TimeInterval,weapon:WeaponDefinition){guard !bots.isEmpty else{return};botCombatAccumulator+=dt;let interval=max(0.1,1.0/max(weapon.fireRate,0.1));while botCombatAccumulator>=interval{botCombatAccumulator-=interval;for s in bots.filter({$0.alive}){guard let t=bots.first(where:{$0.alive&&$0.team != s.team}) else{return};_ = fire(weapon:weapon,from:s.id,at:t.id)}}}
 func tick(dt:TimeInterval){elapsed+=dt;objectiveTicks+=1;if Int(elapsed*4)>shotsFired{shotsFired+=1;if !bots.isEmpty{bots[shotsFired%bots.count].shots+=1}};if let o=objective{switch objectiveState{case .planting:objectiveElapsed+=dt;if objectiveElapsed>=o.plantDuration{objectiveState = .planted;objectiveElapsed=0};case .planted:objectiveElapsed+=dt;if objectiveElapsed>=o.fuseDuration{objectiveState = .detonated;scoreAttack+=1};case .defusing:objectiveElapsed+=dt;if objectiveElapsed>=o.defuseDuration{objectiveState = .defused;scoreDefense+=1};case .idle,.detonated,.defused:break}};if elapsed>=120{if objectiveState == .idle{scoreDefense+=1};resetRound()}}
}
